import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// Import Components
import Hero from '../components/Hero';
import Farmer_Meat from '@/components/Farmer_Meat';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero source={'./videos/hero-video.mp4'}/>
        <Farmer_Meat product={'beef'}/>
        <Farmer_Meat product={'pig'}/>
        <Farmer_Meat product={'chicken'}/>

      </main>
    </>
  )
}
