import { useState, useEffect } from "react";

import Head from 'next/head';
import styles from '@/styles/Home.module.css';

// Import Components
import Hero from '../components/Hero';
import AllFood from '@/components/Food/AllFood';

export default function Home() {

  const [food, setFood] = useState([]);
  const [isLoading, setLoading] = useState(false)

  async function fetchFood() {
    const response = await fetch('http://localhost:3000/api/food');
    // waits until the request completes...
    console.log(response);
  }

  console.log(fetchFood())

  useEffect(() => {
    setLoading(true)
    // const fetching = await fetch('http://localhost:3000/api/food')
    fetch('http://localhost:3000/api/food')
      .then((res) => {
        console.log(res)
      })
      .then((data) => {
        setFood(data)
        setLoading(false)
      })
  }, []);

  // if (isLoading) return <p>Loading...</p>

  // if (!food) return <p>No Farm Data Yet, Sad Face</p>

  const FoodData = () => {
    if (isLoading) return <p>Loading...</p>

    if (!food) return <p>No Farm Data Yet, Sad Face</p>

    return <AllFood food={food} setFood={setFood} />
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero source={'./videos/hero-video.mp4'} />

        <FoodData />
      </main>
    </>
  )
}
