import { useState, useEffect } from "react";

import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

// Import Components
import Hero from '../components/Hero';
import AllFood from '@/components/Food/AllFood';

export default function Home() {

  const [food, setFood] = useState([]);

  useEffect(() => {
    (async () => {
      const getFood = await fetch("/api/food");
      // debugger;
      const getFoodJson = await getFood.json();
      setFood(getFoodJson);

      setIsLoading(false);
    })();
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero source={'./videos/hero-video.mp4'}/>
        <AllFood food={food} setFood={setFood} />
      </main>
    </>
  )
}
